// clang-format off
static const char tab_css[] =
    "#album-picture { "
    "}"
    "#album-name { "
        "font-family: \"Noto Sans Mono\"; "
        "font-size: 13px; "
        "border: none;"
    "}"
    "#album-name:hover { "
        "background-color: inherit;"
    "}"
    "#popalbum-list:hover {"
        "background-color: inherit;"
    "}"
    "#listbox {"
        "background-color: inherit;"
    "}"
    "#listbox:hover {"
        "background-color: inherit;"
    "}"
    ;
